<<<<<<< HEAD
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - baseline-browser-mapping
  - electron-to-chromium
  - semver
allowBuilds:
  "@parcel/watcher": true
  "@tailwindcss/oxide": true
  electron: true
  esbuild: true
  javascript-obfuscator: true
=======
allowBuilds:
  '@parcel/watcher': true
>>>>>>> 4a9344276d925a83e32726c58b9b05debdf4a8ad
  unrs-resolver: true
  vue-demi: true
