<<<<<<< HEAD
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - baseline-browser-mapping
  - electron-to-chromium
  - semver
allowBuilds:
  "@parcel/watcher": true
  "@tailwindcss/oxide": true
  electron: true
  esbuild: true
  javascript-obfuscator: true
=======
allowBuilds:
  '@parcel/watcher': true
>>>>>>> 9c69ceb712d475b9a9bd31fc9b787240061a05a5
  unrs-resolver: true
  vue-demi: true
