<<<<<<< HEAD
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - baseline-browser-mapping
  - electron-to-chromium
  - semver
allowBuilds:
  "@parcel/watcher": true
  "@tailwindcss/oxide": true
  electron: true
  esbuild: true
  javascript-obfuscator: true
=======
allowBuilds:
  '@parcel/watcher': true
>>>>>>> ffcef6e22b372e2f3dcc1048bf50073234505d74
  unrs-resolver: true
  vue-demi: true
